# Setup
title: 성장형 초보 개발자
description: 더 나은 나로 성장하기 위해 노력하자
url: https://rhkdgur.github.io/
avatar: /profile.PNG
paginate: 5
permalink: pretty
cover_image: /code.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Songzi Vong
  links:
    - 
    - https://github.com/rhkdgur
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Go Gwang Hyeok
  url: https://github.com/rhkdgur
  email: rhkdgur@gmail.com
